### ISSUE TITLE
When you create a div, the number of vertices increases dramatically, so there is no point in creating a div.

### ISSUE THREAD

**Issue by MariallenaHax** [MapStudioProject/CTR-Studio#69]
If, for some reason, you decide to create a div, all the faces will be separated. This will lead to an explosion of vertices and a slowdown.

**Comment by MariallenaHax** [comment]
The latest commit of CtrLibrary has reduced the problem of increasing vertices that caused lag, but now there is a problem of models disappearing in unexpected places.
Also, in theory it is possible to reduce the number of vertices even further, but I don't know.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/MapStudioProject/CTR-Studio/commit/4fb1850c6cb751eac046cbd35988344ae601d50c

The vertices just remove duplicates by comparing the contents. One of the better ways to optimize it is if you can remove vertex normals as that is the other reason dupe vertices can exist since they can be angled differently at the same point. Most 3DS tracks don't need these and use vertex colors to do shading.  Currently normals are always imported unless they are all the same value for a mesh or none exist, so it has to be modifed in a 3d editor atm.
